// src/mockData.js
export const events = [
    {
        id: 1,
        title: "Rishi Rich Live",
        showType: "Music Concert",
        language: "Hindi, Punjabi",
        category: "Live Music",
        price: 2999,
        location: "Jawaharlal Nehru Stadium, Delhi",
        dateTime: "2024-11-25T19:00:00",
        imageUrl: "https://images.unsplash.com/photo-1581957220666-5a4b6e3d1f27?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTc3M3wwfDF8c2VhcmNofDExfHxtdXNpYyUyMGNvbmNlcnR8ZW58MHx8fHwxNjk5NzY4MzI3&ixlib=rb-1.2.1&q=80&w=400",
        description: "Join Rishi Rich for an electrifying night of music and energy at one of Delhi's iconic venues!"
    },
    {
        id: 2,
        title: "The Comedy Show with Kenny Sebastian",
        showType: "Stand-Up Comedy",
        language: "English",
        category: "Comedy",
        price: 1500,
        location: "St. Andrew's Auditorium, Mumbai",
        dateTime: "2024-12-08T20:00:00",
        imageUrl: "https://images.unsplash.com/photo-1557691263-307c55bbcc12?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTc3M3wwfDF8c2VhcmNofDJ8fGtvbWVkeSUyMHNoYXclMjBjb21lZHl8ZW58MHx8fHwxNjk5NzY4MzYw&ixlib=rb-1.2.1&q=80&w=400",
        description: "Laugh out loud with Kenny Sebastian as he brings his unique comedic style to Mumbai!"
    },
    {
        id: 3,
        title: "Chennai International Film Festival",
        showType: "Film Festival",
        language: "Various",
        category: "Film",
        price: 500,
        location: "Various Theaters, Chennai",
        dateTime: "2024-12-14T10:00:00",
        imageUrl: "https://images.unsplash.com/photo-1582650318228-b7e7de82ed3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTc3M3wwfDF8c2VhcmNofDEyfHxlbGVjdHJvbmljfGVufDB8fHx8MTY5OTc2ODQwOQ&ixlib=rb-1.2.1&q=80&w=400",
        description: "Celebrate cinema from around the world at the Chennai International Film Festival, featuring screenings, discussions, and more!"
    },
    {
        id: 4,
        title: "Hyderabad Fashion Week 2024",
        showType: "Fashion Show",
        language: "English",
        category: "Fashion",
        price: 1000,
        location: "HICC, Hyderabad",
        dateTime: "2024-12-30T17:00:00",
        imageUrl: "https://images.unsplash.com/photo-1560781240-9ff74f8b2c5e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTc3M3wwfDF8c2VhcmNofDE0fHxmb3NoaW9ufGVufDB8fHx8MTY5OTc2ODQ4Ng&ixlib=rb-1.2.1&q=80&w=400",
        description: "Witness the latest trends and styles at Hyderabad Fashion Week featuring top designers and models!"
    },
    {
        id: 5,
        title: "Bangalore Literature Festival 2024",
        showType: "Literature Festival",
        language: "English, Kannada",
        category: "Literature",
        price: 750,
        location: "Jayamahal Palace Hotel, Bangalore",
        dateTime: "2025-01-05T10:00:00",
        imageUrl: "https://images.unsplash.com/photo-1511333634892-739f7c2b5378?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTc3M3wwfDF8c2VhcmNofDIyfHxsZXQlMjBmb3J1bXxlbnwwfHx8fDE2OTk3Njg0MDE&ixlib=rb-1.2.1&q=80&w=400",
        description: "Join authors, poets, and literary enthusiasts for engaging sessions and discussions at the Bangalore Literature Festival."
    },
    {
        id: 6,
        title: "Delhi Art Fair",
        showType: "Art Exhibition",
        language: "English, Hindi",
        category: "Art",
        price: 300,
        location: "Pragati Maidan, Delhi",
        dateTime: "2025-01-12T11:00:00",
        imageUrl: "https://images.unsplash.com/photo-1578923721800-53702256b40b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTc3M3wwfDF8c2VhcmNofDd8fGFydCUyMGV4aGliaXRpb258ZW58MHx8fHwxNjk5NzY5MjMy&ixlib=rb-1.2.1&q=80&w=400",
        description: "Explore contemporary art from renowned artists at the Delhi Art Fair. A must-visit for art lovers!"
    },
    {
        id: 7,
        title: "Bollywood Retro Night",
        showType: "Music Concert",
        language: "Hindi",
        category: "Music",
        price: 2500,
        location: "Jio World Garden, Mumbai",
        dateTime: "2024-11-30T18:30:00",
        imageUrl: "https://images.unsplash.com/photo-1522742943744-28485e0fbfd3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTc3M3wwfDF8c2VhcmNofDh8fG11c2ljJTIwY29uY2VydHxlbnwwfHx8fDE2OTk3NjkyNDc&ixlib=rb-1.2.1&q=80&w=400",
        description: "Get grooving with retro Bollywood hits performed live by top musicians and singers in Mumbai."
    },
    {
        id: 8,
        title: "Chennai Super Kings Fan Fest",
        showType: "Sports Event",
        language: "English, Tamil",
        category: "Sports",
        price: 200,
        location: "M.A. Chidambaram Stadium, Chennai",
        dateTime: "2025-01-15T16:00:00",
        imageUrl: "https://images.unsplash.com/photo-1517649763962-0c623066013b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTc3M3wwfDF8c2VhcmNofDh8fHNwb3J0cyUyMGV2ZW50fGVufDB8fHx8MTY5OTc2OTI2MA&ixlib=rb-1.2.1&q=80&w=400",
        description: "Celebrate your love for cricket and Chennai Super Kings with fellow fans at this exclusive fan fest."
    },
    {
        id: 9,
        title: "Hyderabad Tech Summit 2024",
        showType: "Tech Conference",
        language: "English",
        category: "Technology",
        price: 3500,
        location: "HITEX Exhibition Center, Hyderabad",
        dateTime: "2024-12-20T09:00:00",
        imageUrl: "https://images.unsplash.com/photo-1581091870621-2b00c2b2e4e9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTc3M3wwfDF8c2VhcmNofDEwfHx0ZWNobm9sb2d5JTIwY29uZmVyZW5jZXxlbnwwfHx8fDE2OTk3NjkyNzY&ixlib=rb-1.2.1&q=80&w=400",
        description: "Join industry experts at the Hyderabad Tech Summit to discuss the latest advancements in technology and innovation."
    },
    {
        id: 10,
        title: "Bangalore Food Carnival",
        showType: "Food Festival",
        language: "English, Kannada",
        category: "Food & Drink",
        price: 500,
        location: "Lalbagh Botanical Garden, Bangalore",
        dateTime: "2025-02-10T12:00:00",
        imageUrl: "https://images.unsplash.com/photo-1543353071-873f17a7a088?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTc3M3wwfDF8c2VhcmNofDN8fGZvb2QlMjBmZXN0aXZhbHxlbnwwfHx8fDE2OTk3NjkyOTE&ixlib=rb-1.2.1&q=80&w=400",
        description: "Enjoy a variety of cuisines, live cooking demonstrations, and food-related activities at the Bangalore Food Carnival."
    },
    {
        id: 11,
        title: "Delhi Poetry Slam",
        showType: "Poetry Reading",
        language: "English, Hindi",
        category: "Literature",
        price: 200,
        location: "India Habitat Centre, Delhi",
        dateTime: "2025-01-18T18:00:00",
        imageUrl: "https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTc3M3wwfDF8c2VhcmNofDh8fHBvZXRyeSUyMHJlYWRpbmd8ZW58MHx8fHwxNjk5NzY5Mjgx&ixlib=rb-1.2.1&q=80&w=400",
        description: "Express yourself through poetry or enjoy listening to poets share their work at the Delhi Poetry Slam."
    },
    {
        id: 12,
        title: "Mumbai Theatre Festival",
        showType: "Theatre",
        language: "English, Marathi",
        category: "Drama",
        price: 1200,
        location: "Prithvi Theatre, Mumbai",
        dateTime: "2024-12-27T19:00:00",
        imageUrl: "https://images.unsplash.com/photo-1584351583153-f9c2a9bfeeb3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTc3M3wwfDF8c2VhcmNofDZ8fHRoZWF0cmV8ZW58MHx8fHwxNjk5NzY5Mjk4&ixlib=rb-1.2.1&q=80&w=400",
        description: "Experience a variety of plays ranging from classic dramas to modern storytelling at the Mumbai Theatre Festival."
    },
    {
        id: 13,
        title: "Chennai Dance Extravaganza",
        showType: "Dance Show",
        language: "Tamil, English",
        category: "Dance",
        price: 800,
        location: "Music Academy, Chennai",
        dateTime: "2025-02-05T17:00:00",
        imageUrl: "https://images.unsplash.com/photo-1562967916-eb82221dfb33?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTc3M3wwfDF8c2VhcmNofDF8fGRhbmNlJTIwcGVyZm9ybWFuY2V8ZW58MHx8fHwxNjk5NzY5MzEx&ixlib=rb-1.2.1&q=80&w=400",
        description: "Watch stunning dance performances from traditional to contemporary styles at the Chennai Dance Extravaganza."
    },
    {
        id: 14,
        title: "Hyderabad Start-up Summit",
        showType: "Business Conference",
        language: "English",
        category: "Business",
        price: 4000,
        location: "T-Hub, Hyderabad",
        dateTime: "2025-02-20T09:30:00",
        imageUrl: "https://images.unsplash.com/photo-1504386106331-3e4e71712b38?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTc3M3wwfDF8c2VhcmNofDh8fHN0YXJ0dXAlMjBzdW1taXR8ZW58MHx8fHwxNjk5NzY5MzMz&ixlib=rb-1.2.1&q=80&w=400",
        description: "Network with entrepreneurs and investors at the Hyderabad Start-up Summit, where innovation meets business."
    },
   
  
    {
        id: 16,
        title: "Bangalore Music Fiesta",
        showType: "Music Festival",
        language: "English, Kannada, Hindi",
        category: "Music",
        price: 3500,
        location: "Bangalore Palace Grounds",
        dateTime: "2025-03-12T18:00:00",
        imageUrl: "https://images.unsplash.com/photo-1534050359320-4fe6eb1f1129?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTc3M3wwfDF8c2VhcmNofDF8fG11c2ljJTIwZmVzdGl2YWx8ZW58MHx8fHwxNjk5NzY5MzUx&ixlib=rb-1.2.1&q=80&w=400",
        description: "A multi-genre music festival featuring local and international artists, celebrating diverse music styles in Bangalore."
    },
    {
        id: 17,
        title: "Delhi Vintage Car Show",
        showType: "Car Exhibition",
        language: "English",
        category: "Exhibition",
        price: 700,
        location: "Nehru Park, Delhi",
        dateTime: "2025-02-28T10:00:00",
        imageUrl: "https://images.unsplash.com/photo-1497115010541-6205ff7ab4e1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTc3M3wwfDF8c2VhcmNofDh8fHZpbnRhZ2UlMjBjYXJ8ZW58MHx8fHwxNjk5NzY5MzYy&ixlib=rb-1.2.1&q=80&w=400",
        description: "Admire classic cars from various eras at the Delhi Vintage Car Show. A treat for automobile enthusiasts."
    },
    {
        id: 18,
        title: "Mumbai Literature Festival",
        showType: "Literary Event",
        language: "English, Marathi, Hindi",
        category: "Literature",
        price: 300,
        location: "Tata Theatre, NCPA, Mumbai",
        dateTime: "2025-01-20T11:00:00",
        imageUrl: "https://images.unsplash.com/photo-1509475237952-5035f6f10f77?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTc3M3wwfDF8c2VhcmNofDF8fGxpdGVyYXR1cmUlMjBldmVudHxlbnwwfHx8fDE2OTk3NjkzNzU&ixlib=rb-1.2.1&q=80&w=400",
        description: "Meet authors, attend book readings, and participate in literary discussions at the Mumbai Literature Festival."
    },
    {
        id: 19,
        title: "Chennai Kite Festival",
        showType: "Outdoor Activity",
        language: "English, Tamil",
        category: "Festival",
        price: 150,
        location: "Marina Beach, Chennai",
        dateTime: "2025-03-01T10:00:00",
        imageUrl: "https://images.unsplash.com/photo-1485243783610-cf70f3cd10c5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTc3M3wwfDF8c2VhcmNofDJ8fGtpdGUlMjBmZXN0aXZhbHxlbnwwfHx8fDE2OTk3NjkzODg&ixlib=rb-1.2.1&q=80&w=400",
        description: "Fly kites with enthusiasts from across the city and beyond, and enjoy kite-making workshops at the Chennai Kite Festival."
    },
    {
        id: 20,
        title: "Hyderabad Sufi Music Night",
        showType: "Music Concert",
        language: "Urdu, Hindi",
        category: "Music",
        price: 800,
        location: "Shilpakala Vedika, Hyderabad",
        dateTime: "2025-02-14T19:30:00",
        imageUrl: "https://images.unsplash.com/photo-1511919884226-d7f02b106bbb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTc3M3wwfDF8c2VhcmNofDd8fG11c2ljJTIwY29uY2VydHxlbnwwfHx8fDE2OTk3Njk0MDI&ixlib=rb-1.2.1&q=80&w=400",
        description: "Immerse yourself in soulful Sufi music performed by renowned artists in a magical setting."
    },
    {
        id: 21,
        title: "Bangalore Comedy Marathon",
        showType: "Comedy Show",
        language: "English, Kannada, Hindi",
        category: "Comedy",
        price: 1000,
        location: "Good Shepherd Auditorium, Bangalore",
        dateTime: "2025-03-08T18:00:00",
        imageUrl: "https://images.unsplash.com/photo-1515162305280-6d12e865a1b5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTc3M3wwfDF8c2VhcmNofDJ8fGNvbWVkeSUyMHNob3d8ZW58MHx8fHwxNjk5NzY5NDIx&ixlib=rb-1.2.1&q=80&w=400",
        description: "Laugh out loud at this comedy marathon featuring stand-up acts from some of the best comedians across the country."
    },
    {
        id: 22,
        title: "Delhi Street Food Festival",
        showType: "Food Festival",
        language: "Hindi, English",
        category: "Food & Drink",
        price: 400,
        location: "Jawaharlal Nehru Stadium, Delhi",
        dateTime: "2025-03-15T12:00:00",
        imageUrl: "https://images.unsplash.com/photo-1541634991073-b2beb6bc343e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTc3M3wwfDF8c2VhcmNofDJ8fHN0cmVldCUyMGZvb2R8ZW58MHx8fHwxNjk5NzY5NDM1&ixlib=rb-1.2.1&q=80&w=400",
        description: "Indulge in the best street food from across India, all in one place at the Delhi Street Food Festival."
    },
    {
        id: 23,
        title: "Mumbai Yoga Retreat",
        showType: "Wellness Event",
        language: "English, Hindi",
        category: "Health & Wellness",
        price: 2500,
        location: "Powai Lake, Mumbai",
        dateTime: "2025-02-25T06:00:00",
        imageUrl: "https://images.unsplash.com/photo-1528660493886-8ec007f6dff2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTc3M3wwfDF8c2VhcmNofDJ8fHlvZ2ElMjByZXRyZWF0fGVufDB8fHx8MTY5OTc2OTQ0NQ&ixlib=rb-1.2.1&q=80&w=400",
        description: "Find your inner peace and improve your well-being at the Mumbai Yoga Retreat set in a serene environment."
    },
    {
        id: 24,
        title: "Chennai Film Festival",
        showType: "Film Screening",
        language: "English, Tamil",
        category: "Film",
        price: 600,
        location: "Sathyam Cinemas, Chennai",
        dateTime: "2025-03-22T17:30:00",
        imageUrl: "https://images.unsplash.com/photo-1512003867696-6d34c4e42f87?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTc3M3wwfDF8c2VhcmNofDd8fGZpbG0lMjBzY3JlZW5pbmd8ZW58MHx8fHwxNjk5NzY5NDU1&ixlib=rb-1.2.1&q=80&w=400",
        description: "Catch screenings of acclaimed films from around the world and meet filmmakers at the Chennai Film Festival."
    },
    
    {
        id: 25,
        title: "Hyderabad Coding Bootcamp",
        showType: "Workshop",
        language: "English",
        category: "Education",
        price: 5000,
        location: "T-Hub, Hyderabad",
        dateTime: "2025-03-05T09:00:00",
        imageUrl: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTc3M3wwfDF8c2VhcmNofDR8fGJvb3RjYW1wfGVufDB8fHx8MTY5OTc2OTQ3MA&ixlib=rb-1.2.1&q=80&w=400",
        description: "An intensive coding bootcamp for beginners and experienced developers to learn new technologies and improve coding skills."
    },
    {
        id: 26,
        title: "Bangalore Fitness Marathon",
        showType: "Fitness Event",
        language: "English, Kannada",
        category: "Health & Wellness",
        price: 600,
        location: "Kanteerava Stadium, Bangalore",
        dateTime: "2025-03-18T05:30:00",
        imageUrl: "https://images.unsplash.com/photo-1594187120521-44f1d4a823dd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTc3M3wwfDF8c2VhcmNofDd8fGZpdG5lc3MlMjBtYXJhdGhvbnxlbnwwfHx8fDE2OTk3Njk0NzU&ixlib=rb-1.2.1&q=80&w=400",
        description: "Participate in the Bangalore Fitness Marathon and challenge yourself to complete a run while promoting health and wellness."
    },
    {
        id: 27,
        title: "Delhi International Jazz Festival",
        showType: "Music Concert",
        language: "English",
        category: "Music",
        price: 1200,
        location: "Nehru Park, Delhi",
        dateTime: "2025-04-01T19:00:00",
        imageUrl: "https://images.unsplash.com/photo-1543771450-84c163a4e6de?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTc3M3wwfDF8c2VhcmNofDZ8fGphenolMjBjb25jZXJ0fGVufDB8fHx8MTY5OTc2OTQ4OA&ixlib=rb-1.2.1&q=80&w=400",
        description: "Enjoy live performances by top international and Indian jazz artists at the Delhi International Jazz Festival."
    },
    {
        id: 28,
        title: "Mumbai Startup Weekend",
        showType: "Networking Event",
        language: "English",
        category: "Business",
        price: 3500,
        location: "WeWork BKC, Mumbai",
        dateTime: "2025-03-28T10:00:00",
        imageUrl: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTc3M3wwfDF8c2VhcmNofDh8fHN0YXJ0dXAlMjBldmVudHxlbnwwfHx8fDE2OTk3Njk0OTQ&ixlib=rb-1.2.1&q=80&w=400",
        description: "Meet entrepreneurs, developers, and business mentors for a weekend full of networking and business ideas at Mumbai Startup Weekend."
    },
    {
        id: 29,
        title: "Chennai Art and Craft Workshop",
        showType: "Art Workshop",
        language: "English, Tamil",
        category: "Art",
        price: 1000,
        location: "Phoenix Market City, Chennai",
        dateTime: "2025-04-05T14:00:00",
        imageUrl: "https://images.unsplash.com/photo-1493585552824-131927f0b5e4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTc3M3wwfDF8c2VhcmNofDF8fGFydCUyMHdvcmtzaG9wfGVufDB8fHx8MTY5OTc2OTUwNw&ixlib=rb-1.2.1&q=80&w=400",
        description: "Explore your creative side at this art and craft workshop in Chennai. Suitable for all age groups."
    },
    {
        id: 30,
        title: "Hyderabad Classic Rock Night",
        showType: "Music Concert",
        language: "English",
        category: "Music",
        price: 800,
        location: "Heart Cup Coffee, Hyderabad",
        dateTime: "2025-03-25T19:00:00",
        imageUrl: "https://images.unsplash.com/photo-1514361892636-04a08ac778a6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTc3M3wwfDF8c2VhcmNofDh8fGNsYXNzaWMlMjByb2NrJTIwY29uY2VydHxlbnwwfHx8fDE2OTk3Njk1MTc&ixlib=rb-1.2.1&q=80&w=400",
        description: "Relive the magic of classic rock music at the Hyderabad Classic Rock Night, featuring performances from local bands."
    },
    {
        id: 31,
        title: "Bangalore Kids Carnival",
        showType: "Children's Event",
        language: "English, Kannada",
        category: "Family",
        price: 500,
        location: "Cubbon Park, Bangalore",
        dateTime: "2025-03-21T10:00:00",
        imageUrl: "https://images.unsplash.com/photo-1531379410505-7c38e93a0dbe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTc3M3wwfDF8c2VhcmNofDd8fGtpZHMlMjBhY3Rpdml0eXxlbnwwfHx8fDE2OTk3Njk1MzQ&ixlib=rb-1.2.1&q=80&w=400",
        description: "A fun-filled day for children featuring games, activities, and performances at the Bangalore Kids Carnival."
    },
    {
        id: 100,
        title: "Mumbai Dance Fest",
        showType: "Dance Show",
        language: "Hindi, English",
        category: "Dance",
        price: 1200,
        location: "Nehru Centre, Mumbai",
        dateTime: "2025-01-20T19:30:00",
        imageUrl: "https://images.unsplash.com/photo-1587063629345-fef5ae1c00b5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTc3M3wwfDF8c2VhcmNofDF8fGRhbmNlJTIwc2hvdyUyMG1vbWVudHxlbnwwfHx8fDE2OTk3Njg0NzE&ixlib=rb-1.2.1&q=80&w=400",
        description: "Experience the vibrant world of dance at the Mumbai Dance Fest featuring top performers!"
    }
    
];
